version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/items-marketplace"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/angular-app"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
