name: Deploy Backend

on: workflow_dispatch

jobs:
  ci:
    name: CI
    uses: darkovrbaski/items_marketplace/.github/workflows/ci.yml@main
    secrets: inherit

  release:
    needs: ci
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@18bf8ad2ca49c14cbb28b91346d626ccfb00c518 # v2.1.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      
      - name: Deploy succeed
        run: echo "Deploy succeed"
