name: Deploy Frontend and Backend

on: workflow_dispatch

jobs:
  ci-backend:
    name: CI
    uses: darkovrbaski/items_marketplace/.github/workflows/ci-backend.yml@main
    secrets: inherit
  
  ci-frontend:
    name: CI
    uses: darkovrbaski/items_marketplace/.github/workflows/ci-frontend.yml@main
    secrets: inherit

  release:
    needs: [ci-backend, ci-frontend]
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@18bf8ad2ca49c14cbb28b91346d626ccfb00c518 # v2.1.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      
      - name: Deploy succeed
        run: echo "Deploy succeed"
