name: Dependabot Auto Merge

on: pull_request_target

jobs:
  automerge:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@18bf8ad2ca49c14cbb28b91346d626ccfb00c518 # v2.1.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: fastify/github-action-merge-dependabot@be73043be1228aa39e89a1c4e4187db6a50b3251 # v3.5.4
        if: ${{ github.actor == 'dependabot[bot]' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
